### ISSUE TITLE
Update Category bug

### ISSUE THREAD

**Issue by zhanhui913** [zhanhui913/Budget#10]
After updating a category, and you click save; it bugs out (where category color and icon is 0)

```

12 17:31:34.927 23218-23218/com.zhan.budget I/ZHAN: ----------- onActivityResult ----------
02-12 17:31:34.927 23218-23218/com.zhan.budget D/ZHAN: category name is Dinner
02-12 17:31:34.927 23218-23218/com.zhan.budget D/ZHAN: category color is 0
02-12 17:31:34.927 23218-23218/com.zhan.budget D/ZHAN: category icon is 0
02-12 17:31:34.927 23218-23218/com.zhan.budget D/ZHAN: category budget is -200.0
02-12 17:31:34.927 23218-23218/com.zhan.budget I/ZHAN: ----------- onActivityResult ----------
02-12 17:31:34.927 23218-23218/com.zhan.budget I/ZHAN: eddited index :2
02-12 17:31:35.057 23218-23218/com.zhan.budget W/ResourceType: No package identifier when getting value for resource number 0x00000000
02-12 17:31:35.077 23218-23218/com.zhan.budget E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.zhan.budget, PID: 23218
                                                                 android.content.res.Resources$NotFoundException: Resource ID #0x0
                                                                     at android.content.res.Resources.getValue(Resources.java:1245)
                                                                     at android.content.res.Resources.getColor(Resources.java:899)
                                                                     at android.support.v4.content.ContextCompat.getColor(ContextCompat.java:368)
                                                                     at com.zhan.circularview.CircularView.setCircleColor(CircularView.java:219)
                                                                     at com.zhan.budget.Adapter.CategoryListAdapter.getView(CategoryListAdapter.java:154)
                                                                     at android.widget.AbsListView.obtainView(AbsListView.java:2467)
                                                                     at android.widget.ListView.makeAndAddView(ListView.java:1864)
```

**Comment by zhanhui913** [comment]
Fixed 33ad39341740d3fa769980d7e6bf81a3e6f132a9
